all: parser

test_parser.tab.c test_parser.tab.h: test_parser.y
	bison -t -v -d test_parser.y

lex.yy.c: test_lexer.l test_parser.tab.h
	flex test_lexer.l

parser: lex.yy.c test_parser.tab.c test_parser.tab.h
	gcc -o parser test_parser.tab.c lex.yy.c
	./parser TestProg.cmm

clean:
	rm -f parser lexer test_parser.tab.c lex.yy.c test_parser.tab.h test_parser.output
	ls -l
